In [17]:
import gymnasium as gym
env = gym.make('CarRacing-v2', render_mode="human")
obs, info = env.reset()

for i in range(1000):
    action = env.action_space.sample() # agent policy that uses the obs and info
    obs, r, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        obs, info = env.reset()

env.close()

In [18]:
print(env.action_space)
print(env.observation_space)


Box([-1.  0.  0.], 1.0, (3,), float32)
Box(0, 255, (96, 96, 3), uint8)


In [20]:
import gymnasium as gym
from gymnasium.wrappers import FlattenObservation
env = gym.make("CarRacing-v2")
print(env.observation_space.shape)
env = FlattenObservation(env)
print(env.observation_space.shape)
print(96*96*3)

(96, 96, 3)
(27648,)
27648


In [27]:
from gymnasium.spaces import Box
import numpy as np
space_1 = Box(low=-1.0, high=2.0, shape=(2,3), dtype=np.float32)
print(space_1)
print(space_1.sample())

space_2 = Box(low=np.array([-1.0, 1.0]), high=np.array([0.0, 4.0]), dtype=np.float32)
print(space_2)
print(space_2.sample())

space_3 = Box(low=0.0,high=3.0)
print(space_3)
print(space_3.sample())

Box(-1.0, 2.0, (2, 3), float32)
[[ 1.9909168  1.3377541  1.7167282]
 [ 0.6715995 -0.8229317  0.7395049]]
Box([-1.  1.], [0. 4.], (2,), float32)
[-0.9841588  2.7773   ]
Box(0.0, 3.0, (1,), float32)
[2.4251857]


c:\ProgramData\Anaconda3\envs\RL\lib\site-packages\gymnasium\spaces\box.py:129: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [35]:
from gymnasium.spaces import Discrete
space_1 = Discrete(2)
print(space_1)
space_2 = Discrete(3, start=-2)
print(space_2)
print(space_2.sample())

Discrete(2)
Discrete(3, start=-2)
-1


In [37]:
from gymnasium.spaces import MultiBinary
space_1 = MultiBinary(5)
print(space_1)
print(space_1.sample())
space_2 = MultiBinary([3,5])
print(space_2.sample())

MultiBinary(5)
[1 1 0 1 1]
[[1 0 1 1 1]
 [1 0 1 0 0]
 [0 1 1 0 1]]


In [47]:
from gymnasium.spaces import MultiDiscrete
space_1 = MultiDiscrete([5,3,3])
print(space_1.sample())
space_2 = MultiDiscrete(np.array([[2,3],[3, 4]]))
print(space_2.sample())

[0 0 1]
[[1 1]
 [2 3]]


In [48]:
from gymnasium.spaces import Text
import string
space_1 = Text(5)
print(space_1)
print(space_1.sample())

space_2 = Text(min_length=1, max_length=10, charset=string.digits)
print(space_2)
print(space_2.sample())


Text(1, 5, characters=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz)
YjFNT
Text(1, 10, characters=0123456789)
436


In [52]:
# Composite Spaces
from gymnasium.spaces import Dict, Box, Discrete
space = Dict({"position": Box(-1,1,shape=(2,)), "color":Discrete(3)})
print(space)
print(space.sample())

Dict('color': Discrete(3), 'position': Box(-1.0, 1.0, (2,), float32))
OrderedDict([('color', 0), ('position', array([0.19309135, 0.5977046 ], dtype=float32))])


In [54]:
from gymnasium.spaces import Graph, Box, Discrete
observation_space = Graph(node_space=Box(low=-100, high=100, shape=(3,)), edge_space=Discrete(3))
print(observation_space)
print(observation_space.sample())

Graph(Box(-100.0, 100.0, (3,), float32), Discrete(3))
GraphInstance(nodes=array([[-81.37034  ,  64.22826  ,  56.43789  ],
       [-59.464783 , -74.479126 , -57.83826  ],
       [-55.259315 , -21.026602 , -52.232952 ],
       [  6.1740503,  -6.3199534,   4.9646454],
       [ 43.65353  ,  77.879684 ,   2.9875448],
       [-92.17555  ,  18.167559 ,  95.547264 ],
       [-96.210945 , -63.4907   , -38.480637 ],
       [ 95.61307  , -70.55864  ,  73.789314 ],
       [-36.505764 ,  84.08306  ,  46.61411  ],
       [ 20.87842  , -52.376415 , -81.9868   ]], dtype=float32), edges=array([0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 1, 1,
       0, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 0, 2, 0,
       2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 0, 2, 2,
       1, 2, 1, 1, 2, 1, 0, 0, 0, 2, 1, 0], dtype=int64), edge_links=array([[6, 7],
       [7, 5],
       [5, 3],
       [2, 9],
       [5, 9],
       [9, 8],
       [6, 5],
       [4, 9],
       [4, 4],


In [1]:
import gymnasium as gym
from gymnasium.wrappers import ClipAction
env = gym.make("Hopper-v4")
env = ClipAction(env)
print(env.action_space)

ValueError: XML Error: global coordinates no longer supported. To convert existing models, load and save them in MuJoCo 2.3.3 or older
Element 'compiler', line 2
