In [2]:
import numpy as np

np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
array = np.array([[1,2],[3,4],[6,5]])
tmp = array.max(axis=1)
print(tmp)
print(tmp.size)
tmp[1]

[2 4 6]
3


4

In [18]:
array = np.full((10, 2), 0.5)
array

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [19]:
import numpy as np

# 创建一个形状为(10, 2)的数组，每一行的两个元素之和为1
# 使用随机数填充这些元素
array = np.random.rand(10, 2)
array /= np.sum(array, axis=1, keepdims=True)

# 打印数组
print(array)


[[0.98633471 0.01366529]
 [0.33428283 0.66571717]
 [0.24548548 0.75451452]
 [0.50474386 0.49525614]
 [0.57834392 0.42165608]
 [0.39043569 0.60956431]
 [0.67525327 0.32474673]
 [0.99677874 0.00322126]
 [0.52810236 0.47189764]
 [0.75065988 0.24934012]]


In [23]:
pos = 0
tmp = 0 if pos == -1 else -1
tmp

-1

In [24]:
array = np.random.rand(10, 2)
array /= np.sum(array, axis=1, keepdims=True)
for i in range(10):
    print(array[i])
    print(array[i][0])
    print(array[i][1])

[0.54603627 0.45396373]
0.5460362700406999
0.4539637299593001
[0.76015233 0.23984767]
0.7601523273518154
0.23984767264818463
[0.52281579 0.47718421]
0.5228157877950657
0.47718421220493434
[0.70816583 0.29183417]
0.7081658311399874
0.29183416886001257
[0.66225774 0.33774226]
0.662257743834375
0.33774225616562503
[0.18909426 0.81090574]
0.18909425892940207
0.8109057410705979
[0.50548103 0.49451897]
0.5054810258335382
0.4945189741664618
[0.87491495 0.12508505]
0.8749149502825382
0.12508504971746184
[0.41757877 0.58242123]
0.41757877462164367
0.5824212253783564
[0.29066081 0.70933919]
0.2906608078991979
0.7093391921008022
